import fs from "node:fs";
import path from "node:path";

const rules = {
  la: ["Là for identity and roles", "Là links a person or thing to an identity, role, category, or description. It is common with nouns, professions, and introductions.", "Use là for what something is, not before an ordinary action verb.", [0]],
  question: ["Question words in their normal position", "Ai, gì, ở đâu, khi nào, thế nào, và tại sao stay where the missing information would appear. Vietnamese does not move them to the front like English often does.", "Question words keep statement word order; yes-no questions can use không or à depending on context.", [1, 7, 10, 13]],
  time: ["Time expressions before the action", "Vietnamese commonly places time expressions before the verb, and the verb itself does not conjugate for tense. Context words such as hôm qua, đang, rồi, and sẽ carry timing.", "Do not add an English-style past-tense ending to Vietnamese verbs.", [2, 3, 9, 11, 14]],
  dang: ["Đang for actions in progress", "Đang before a verb marks an action that is happening or developing at the relevant time.", "Đang describes an ongoing action; it does not automatically mean every present-tense verb.", [3, 8, 15]],
  location: ["Ở for location", "Ở introduces a place where a person or thing is located. It can also appear in common location phrases such as ở nhà and ở trường.", "Use ở for location, not as a general equivalent of English ‘is’.", [4, 5, 7, 13, 15]],
  measure: ["Classifiers after numbers", "Vietnamese often uses classifiers such as cái, chiếc, quyển, tờ, ly, and người between a number or demonstrative and a noun.", "Choose a classifier that fits the noun instead of translating English number + noun word for word.", [2, 5, 6, 9, 14]],
  cua: ["Của for possession", "Của links an owner to a noun: A của B means B's A or A belonging to B. Possessive pronouns can also be used when the noun is understood.", "Keep the owner and possessed noun in the Vietnamese order: noun + của + owner.", [0, 4, 8, 9, 10, 13]],
  da: ["Đã, rồi, chưa for completed events", "Đã marks an earlier or completed event, rồi often confirms that something has happened, and chưa asks whether it has happened yet or says it has not.", "Vietnamese marks aspect and time with separate words; verbs do not change form.", [2, 5, 9, 11, 14, 16, 18]],
  modal: ["Có thể, muốn, cần, nên, phải", "Modal expressions come before the main verb. Có thể expresses ability or possibility, muốn intention, cần need, nên advice, and phải obligation.", "Do not add a second modal or an English infinitive marker after these expressions.", [1, 7, 8, 9, 11, 13, 16, 18]],
  comparison: ["Comparisons with hơn and bằng", "Put hơn after an adjective or adverb to mean more or -er, and use bằng for equality. Không bằng means not as…as.", "Hơn follows the quality being compared; it does not come before the adjective as English ‘more’ does.", [4, 5, 6, 8, 13, 15]],
  reason: ["Vì… nên… for reasons and results", "Vì introduces a reason and nên introduces the result. The pair explains choices, problems, delays, and solutions.", "Vì gives the cause and nên gives the consequence; keep the logic clear.", [3, 5, 9, 11, 12, 16, 17]],
  condition: ["Nếu… thì… for conditions", "Nếu introduces a condition and thì introduces the expected result. This pattern is useful for plans, warnings, and emergency instructions.", "Thì marks the result; it does not mean every English use of ‘then’.", [6, 7, 11, 15, 17, 18, 19]],
  polite: ["Polite requests with xin, vui lòng, and giúp", "Xin and vui lòng make requests polite, while giúp tôi asks someone to help with a specific action. Tone and relationship still matter.", "A natural request usually states the action clearly instead of repeating xin in every sentence.", [8, 9, 10, 13, 17, 18]],
  passive: ["Bị and được passive patterns", "Bị commonly introduces an unwanted or harmful passive event, while được often introduces a beneficial or permitted one.", "Use a passive pattern when the affected person or object is more important than the actor.", [6, 12, 16, 17, 18, 19]],
  report: ["Sequence and reported information", "First, then, sau đó, lúc đó, and theo lời… organize a report. They make an incident or work update easy to follow.", "Give time, place, people, actions, and results in a clear order.", [10, 11, 12, 18, 19]]
};

const vocab = [
  ["xin chào", "hello", "greeting"], ["cảm ơn", "thank you", "politeness"], ["xin lỗi", "sorry", "politeness"], ["không sao", "it is okay", "phrase"], ["giúp", "help", "verb"],
  ["tôi", "I; me", "pronoun"], ["bạn", "you; friend", "pronoun"], ["anh", "older male; you", "pronoun"], ["chị", "older female; you", "pronoun"], ["chúng tôi", "we; us", "pronoun"], ["mọi người", "everyone", "pronoun"],
  ["công ty", "company", "workplace"], ["văn phòng", "office", "workplace"], ["đồng nghiệp", "coworker", "workplace"], ["quản lý", "manager", "workplace"], ["cuộc họp", "meeting", "workplace"], ["dự án", "project", "workplace"], ["nhiệm vụ", "task", "workplace"], ["tài liệu", "document", "workplace"], ["email", "email", "workplace"], ["máy tính", "computer", "workplace"], ["máy in", "printer", "workplace"], ["khách hàng", "client", "workplace"], ["báo cáo", "report", "workplace"], ["hạn chót", "deadline", "workplace"],
  ["trường học", "school", "school"], ["giáo viên", "teacher", "school"], ["sinh viên", "student", "school"], ["bạn cùng lớp", "classmate", "school"], ["lớp học", "classroom", "school"], ["bài tập", "homework", "school"], ["kỳ thi", "exam", "school"], ["câu hỏi", "question", "school"], ["câu trả lời", "answer", "school"], ["nhóm", "group", "school"], ["thư viện", "library", "school"], ["khuôn viên", "campus", "school"],
  ["nhà", "home", "daily life"], ["phòng", "room", "daily life"], ["chìa khóa", "key", "daily life"], ["hàng xóm", "neighbor", "daily life"], ["siêu thị", "supermarket", "daily life"], ["cửa hàng", "shop", "daily life"], ["tiền", "money", "daily life"], ["giá", "price", "daily life"], ["tàu điện ngầm", "subway", "transport"], ["xe buýt", "bus", "transport"], ["nhà ga", "station", "transport"], ["sân bay", "airport", "transport"], ["đường", "road; way", "transport"], ["bên trái", "left side", "direction"], ["bên phải", "right side", "direction"], ["phía trước", "in front", "direction"], ["phía sau", "behind", "direction"],
  ["bữa sáng", "breakfast", "food"], ["bữa trưa", "lunch", "food"], ["bữa tối", "dinner", "food"], ["nước", "water", "food"], ["cà phê", "coffee", "food"], ["nhà hàng", "restaurant", "food"], ["thực đơn", "menu", "food"], ["nhân viên phục vụ", "server", "food"], ["bệnh viện", "hospital", "health"], ["bác sĩ", "doctor", "health"], ["thuốc", "medicine", "health"], ["cơ thể", "body; health", "health"], ["đau", "hurt; painful", "health"], ["vết thương", "injury", "health"], ["xe cứu thương", "ambulance", "emergency"], ["cảnh sát", "police", "emergency"], ["nguy hiểm", "dangerous; danger", "emergency"], ["tai nạn", "accident", "emergency"], ["điện thoại", "phone", "communication"], ["địa chỉ", "address", "communication"]
].sort((a, b) => b[0].length - a[0].length);

const s = (text, translation) => [text, translation];
const unit = (title, level, ruleId, tags, sentences) => ({ title, level, ruleId, tags, sentences });

const units = [
  unit("Introductions and Roles", "A0", "la", ["introductions", "identity"], [
    s("Xin chào, tôi là Minh.", "Hello, I am Minh."), s("Bạn tên là gì?", "What is your name?"), s("Tôi là nhân viên mới.", "I am the new employee."), s("Chị Lan là quản lý của tôi.", "Ms. Lan is my manager."), s("Anh Nam là đồng nghiệp của tôi.", "Nam is my coworker."), s("Bạn là sinh viên phải không?", "You are a student, right?"), s("Đúng rồi, tôi là sinh viên.", "That's right, I am a student."), s("Đây là bạn cùng lớp của tôi.", "This is my classmate."), s("Tôi làm việc ở một công ty nhỏ.", "I work at a small company."), s("Bạn làm nghề gì?", "What do you do for work?"), s("Tôi là giáo viên tiếng Anh.", "I am an English teacher."), s("Anh ấy là người phụ trách dự án.", "He is the person in charge of the project."), s("Chúng tôi là thành viên của nhóm mới.", "We are members of the new group."), s("Bạn đến từ đâu?", "Where are you from?"), s("Tôi đến từ Đà Nẵng.", "I am from Da Nang."), s("Rất vui được làm quen với bạn.", "Nice to meet you."), s("Xin hãy giúp đỡ tôi trong tuần đầu tiên.", "Please help me during my first week."), s("Bạn có nói tiếng Anh không?", "Do you speak English?"), s("Tôi nói được một ít tiếng Anh.", "I can speak a little English."), s("Bạn bận hôm nay không?", "Are you busy today?"), s("Tôi không bận lắm.", "I am not very busy."), s("Chúng ta có thể nói chuyện một chút.", "We can talk for a little while.")
  ]),
  unit("Names, Clarification, and Communication", "A0", "question", ["questions", "clarification"], [
    s("Tên tiếng Việt của bạn là gì?", "What is your Vietnamese name?"), s("Bạn nói từ nào vậy?", "Which word did you say?"), s("Từ này nghĩa là gì?", "What does this word mean?"), s("Chữ này đọc thế nào?", "How is this character read?"), s("Bạn có thể nói chậm hơn không?", "Can you speak more slowly?"), s("Tôi chưa hiểu câu này.", "I do not understand this sentence yet."), s("Bạn có thể nói lại không?", "Can you say it again?"), s("Tôi sẽ viết xuống.", "I will write it down."), s("Địa chỉ này có đúng không?", "Is this address correct?"), s("Không, tôi nói địa chỉ phía sau.", "No, I mean the address on the back."), s("Nhà vệ sinh ở đâu?", "Where is the restroom?"), s("Bạn cần tìm gì?", "What do you need to find?"), s("Tại sao bạn đến muộn?", "Why are you late?"), s("Vì xe buýt bị trễ.", "Because the bus was delayed."), s("Khi nào lớp học bắt đầu?", "When does class start?"), s("Lớp bắt đầu lúc hai giờ.", "Class starts at two o'clock."), s("Ai có số điện thoại của tôi?", "Who has my phone number?"), s("Tôi có, bạn muốn tôi gửi không?", "I do; do you want me to send it?"), s("Bạn muốn gửi email hay tin nhắn?", "Do you want to send an email or a message?"), s("Tôi muốn gửi tin nhắn vì nhanh hơn.", "I want to send a message because it is faster."), s("Bạn nghe rõ tôi không?", "Can you hear me clearly?"), s("Tôi nghe rõ rồi, cảm ơn.", "I can hear you clearly now, thank you.")
  ]),
  unit("Numbers, Dates, and Schedules", "A0", "time", ["numbers", "time", "schedules"], [
    s("Hôm nay là ngày bao nhiêu?", "What is today's date?"), s("Hôm nay là ngày mười sáu tháng năm.", "Today is May sixteenth."), s("Bây giờ là mấy giờ?", "What time is it now?"), s("Bây giờ là tám giờ rưỡi.", "It is half past eight now."), s("Tôi có một cuộc họp lúc chín giờ.", "I have a meeting at nine."), s("Xin hãy ghi giờ họp vào lịch.", "Please put the meeting time on the calendar."), s("Bạn thức dậy lúc mấy giờ mỗi ngày?", "What time do you wake up every day?"), s("Tôi thức dậy lúc bảy giờ.", "I wake up at seven."), s("Ngày nào có lớp tiếng Việt?", "Which day has Vietnamese class?"), s("Tôi có lớp vào thứ Ba và thứ Năm.", "I have class on Tuesday and Thursday."), s("Tôi có ba tài liệu cần đọc.", "I have three documents to read."), s("Nhiệm vụ này cần bao nhiêu giờ?", "How many hours does this task need?"), s("Tôi cần khoảng hai giờ.", "I need about two hours."), s("Bạn có thể hoàn thành trước năm giờ không?", "Can you finish before five?"), s("Nếu bắt đầu bây giờ thì được.", "If we start now, it is possible."), s("Lớp ngày mai kết thúc lúc mấy giờ?", "What time does tomorrow's class end?"), s("Lớp kết thúc lúc bốn giờ.", "Class ends at four."), s("Tôi đã sắp xếp thời gian rồi.", "I have already arranged the time."), s("Bạn chưa sắp xếp à?", "You have not arranged it yet?"), s("Không sao, chúng ta sắp xếp bây giờ.", "It is okay; we will arrange it now."), s("Xin hãy đến sớm mười phút.", "Please arrive ten minutes early."), s("Được, tôi sẽ không đến muộn.", "Okay, I will not be late.")
  ]),
  unit("Daily Routines", "A0", "dang", ["routine", "habits"], [
    s("Tôi thức dậy lúc sáu giờ rưỡi.", "I wake up at six thirty."), s("Tôi uống một cốc nước trước.", "I drink a glass of water first."), s("Sau đó tôi tắm và ăn sáng.", "Then I shower and eat breakfast."), s("Tôi đi tàu điện ngầm đến công ty.", "I take the subway to the company."), s("Tôi đến văn phòng lúc tám giờ.", "I arrive at the office at eight."), s("Buổi sáng tôi thường có cuộc họp.", "I usually have meetings in the morning."), s("Buổi trưa tôi ăn cùng đồng nghiệp.", "At noon I eat with my coworkers."), s("Buổi chiều tôi trả lời email.", "In the afternoon I answer emails."), s("Bây giờ tôi đang làm một dự án.", "I am working on a project now."), s("Nếu rất bận, tôi mang cơm đến công ty.", "If I am very busy, I bring lunch to the company."), s("Tôi tan làm lúc sáu giờ.", "I finish work at six."), s("Sau giờ làm tôi đi siêu thị.", "After work I go to the supermarket."), s("Tôi mua rau và sữa.", "I buy vegetables and milk."), s("Buổi tối tôi về nhà nấu ăn.", "In the evening I go home and cook."), s("Hôm qua tôi đã nấu rất nhiều thức ăn.", "Yesterday I cooked a lot of food."), s("Hôm nay tôi không muốn nấu ăn.", "Today I do not want to cook."), s("Vì vậy tôi ăn tối ở nhà hàng.", "So I eat dinner at a restaurant."), s("Tôi thích đọc sách vào buổi tối.", "I like reading in the evening."), s("Tôi đi ngủ trước mười một giờ.", "I go to bed before eleven."), s("Cuối tuần tôi dọn phòng.", "I clean my room on weekends."), s("Hôm nay tôi mệt quá rồi.", "I am very tired today."), s("Tôi sẽ đi ngủ sớm hơn.", "I will go to bed earlier.")
  ]),
  unit("Home and Neighborhood", "A0", "location", ["home", "neighborhood"], [
    s("Nhà tôi ở gần ga tàu điện ngầm.", "My home is near the subway station."), s("Phòng của tôi ở tầng hai.", "My room is on the second floor."), s("Chìa khóa ở trên bàn.", "The key is on the table."), s("Máy tính của bạn ở đâu?", "Where is your computer?"), s("Máy tính ở trong phòng.", "The computer is in the room."), s("Có một siêu thị ở tầng dưới.", "There is a supermarket downstairs."), s("Có một công viên bên cạnh nhà tôi.", "There is a park next to my home."), s("Cửa nhà hàng xóm đang mở.", "The neighbor's door is open."), s("Xin hãy đóng cửa lại.", "Please close the door."), s("Tôi đã đóng cửa sổ rồi.", "I have closed the window."), s("Bạn có thể giúp tôi tìm chìa khóa không?", "Can you help me find the key?"), s("Tôi không tìm thấy chìa khóa.", "I cannot find the key."), s("Nếu thấy chìa khóa, hãy nói cho tôi biết.", "If you see the key, let me know."), s("Đèn ở hành lang bị hỏng rồi.", "The hallway light is broken."), s("Tôi đã gọi cho ban quản lý.", "I have called building management."), s("Nhân viên sửa chữa sẽ đến ngày mai.", "The repair worker will come tomorrow."), s("Thùng rác ở ngoài bếp.", "The trash can is outside the kitchen."), s("Con đường này rất yên tĩnh vào ban đêm.", "This road is very quiet at night."), s("Nhà bạn cách trường học xa không?", "Is your home far from school?"), s("Nhà tôi gần hơn trước nhiều.", "My home is much closer than before."), s("Cuối tuần chúng tôi đi bộ quanh đây.", "We walk around here on weekends."), s("Xin hãy cẩn thận ở cầu thang.", "Please be careful on the stairs.")
  ]),
  unit("Food, Cafés, and Restaurants", "A0", "measure", ["food", "restaurant", "requests"], [
    s("Tôi muốn một ly cà phê.", "I would like a cup of coffee."), s("Xin cho tôi một cốc nước nóng.", "Please give me a cup of hot water."), s("Các bạn có mấy chỗ ngồi?", "How many seats do you have?"), s("Chúng tôi có hai người.", "There are two of us."), s("Xin cho chúng tôi một thực đơn.", "Please give us a menu."), s("Món này có cay không?", "Is this dish spicy?"), s("Món này không cay lắm.", "This dish is not very spicy."), s("Tôi không ăn đậu phộng.", "I do not eat peanuts."), s("Nhân viên phục vụ, giúp tôi đổi một bát cơm.", "Server, please help me change to a bowl of rice."), s("Chúng tôi đã gọi món rồi.", "We have already ordered."), s("Còn phải đợi bao lâu?", "How much longer do we need to wait?"), s("Vì bếp rất bận nên phải đợi một lát.", "Because the kitchen is busy, we need to wait a while."), s("Xin hãy đặt bát súp ở đây.", "Please put the bowl of soup here."), s("Bát súp này nóng hơn bát kia.", "This bowl of soup is hotter than that one."), s("Tôi ăn no rồi, cảm ơn.", "I am full, thank you."), s("Cho tôi xin một tờ hóa đơn được không?", "Could I have a bill?"), s("Chúng tôi có thể trả bằng thẻ không?", "Can we pay by card?"), s("Giá ở đây có hợp lý không?", "Are the prices here reasonable?"), s("Nếu không còn chỗ thì chúng ta đi nhà hàng khác.", "If there are no seats, we will go to another restaurant."), s("Tôi đã từng đến quán này.", "I have been to this restaurant before."), s("Dịch vụ ở đây tốt hơn lần trước.", "The service here is better than last time."), s("Cảm ơn bạn đã giới thiệu.", "Thank you for your recommendation.")
  ]),
  unit("Shopping and Payments", "A0", "measure", ["shopping", "money", "payments"], [
    s("Cái này bao nhiêu tiền?", "How much is this?"), s("Chiếc áo này giá bao nhiêu?", "How much is this shirt?"), s("Tôi muốn mua hai chiếc áo trắng.", "I want to buy two white shirts."), s("Có cái nào nhỏ hơn không?", "Do you have a smaller one?"), s("Màu này đẹp hơn màu kia.", "This color is prettier than that one."), s("Xin cho tôi xem một đôi giày khác.", "Please show me another pair of shoes."), s("Tôi có thể thử không?", "Can I try it?"), s("Đôi giày này hơi chật.", "These shoes are a little tight."), s("Tôi cần một cái túi mua hàng.", "I need a shopping bag."), s("Xin hãy cho hóa đơn vào túi.", "Please put the receipt in the bag."), s("Tôi đã trả tiền rồi.", "I have already paid."), s("Bạn chưa trả lại tiền thừa cho tôi.", "You have not given me my change yet."), s("Xin lỗi, tôi sẽ đưa ngay.", "Sorry, I will give it right away."), s("Ở đây có nhận thanh toán bằng điện thoại không?", "Does this place accept mobile payment?"), s("Nếu không có tiền mặt, bạn có thể quẹt thẻ.", "If you do not have cash, you can pay by card."), s("Tôi không tìm thấy ví của mình.", "I cannot find my wallet."), s("Có thể ví ở trên xe.", "The wallet may be in the car."), s("Bạn đã xem ở quầy thu ngân chưa?", "Have you checked the checkout counter?"), s("Tôi đã đi qua đó nhưng không thấy.", "I went there but did not see it."), s("Siêu thị này đóng cửa lúc mười giờ tối.", "This supermarket closes at ten at night."), s("Chúng ta mua nước trước rồi mua trái cây.", "We will buy water first and then fruit."), s("Xin hãy giữ lại tờ hóa đơn này.", "Please keep this receipt.")
  ]),
  unit("Directions and Transportation", "A0", "question", ["transport", "directions", "safety"], [
    s("Ga tàu điện ngầm ở đâu?", "Where is the subway station?"), s("Ga ở bên trái đường.", "The station is on the left side of the road."), s("Xin hãy đi thẳng.", "Please walk straight ahead."), s("Đến ngã tư thì rẽ phải.", "Turn right at the intersection."), s("Tôi nên xuống ở ga nào?", "At which station should I get off?"), s("Bạn xuống ở ga thứ ba.", "Get off at the third station."), s("Xe buýt này có đi sân bay không?", "Does this bus go to the airport?"), s("Xe này không đi sân bay.", "This bus does not go to the airport."), s("Nếu đi tàu điện ngầm thì sẽ nhanh hơn.", "If you take the subway, it will be faster."), s("Tôi đã mua vé rồi.", "I have already bought the ticket."), s("Xin hãy đặt hành lý lên trên.", "Please put the luggage up there."), s("Cẩn thận, đừng đi xuống cầu thang.", "Be careful; do not go down the stairs."), s("Vừa rồi tôi bị lạc ở nhà ga.", "I got lost at the station just now."), s("Bạn có thể gửi địa chỉ cho tôi không?", "Can you send me the address?"), s("Tôi đã tìm thấy lối ra đúng.", "I found the correct exit."), s("Từ đây đi bộ đến trường mất bao lâu?", "How long does it take to walk to school from here?"), s("Đi bộ mất khoảng hai mươi phút.", "Walking takes about twenty minutes."), s("Trời mưa nên đường rất trơn.", "It is raining, so the road is slippery."), s("Xin hãy đợi xe ở nơi an toàn.", "Please wait for the vehicle in a safe place."), s("Tài xế đã dừng xe lại.", "The driver has stopped the vehicle."), s("Tôi đã từng đi tuyến này nhưng không thường xuyên.", "I have taken this route before, but not often."), s("Cảm ơn, lời chỉ đường của bạn rất rõ.", "Thanks, your directions are very clear.")
  ]),
  unit("Office People and Equipment", "A1", "cua", ["office", "coworkers", "equipment"], [
    s("Tôi đang đợi bạn trước văn phòng.", "I am waiting for you in front of the office."), s("Đây là máy tính làm việc của tôi.", "This is my work computer."), s("Kia là bàn của quản lý.", "That is the manager's desk."), s("Tài liệu của bạn ở cạnh máy in.", "Your document is beside the printer."), s("Ai phụ trách dự án này?", "Who is responsible for this project?"), s("Tôi là người phụ trách dự án này.", "I am responsible for this project."), s("Khách hàng của chúng ta đến công ty vào buổi chiều.", "Our client is coming to the company in the afternoon."), s("Xin hãy ghi tên của khách hàng xuống.", "Please write down the client's name."), s("Phòng họp ở cuối hành lang.", "The meeting room is at the end of the hallway."), s("Tôi có thể ngồi bên cạnh bạn không?", "May I sit beside you?"), s("Máy in này có dùng được không?", "Can this printer be used?"), s("Giấy của máy in hết rồi.", "The printer has run out of paper."), s("Xin hãy cho giấy vào máy.", "Please put the paper into the machine."), s("Tôi đã in tài liệu ra rồi.", "I have printed the document."), s("Tài liệu này là của ai?", "Whose document is this?"), s("Đây là tài liệu của đồng nghiệp mới.", "This is the new coworker's document."), s("Xin đừng mở tài liệu của người khác.", "Please do not open other people's documents."), s("Nếu máy tính hỏng thì hãy nói cho tôi biết.", "If the computer breaks, tell me."), s("Màn hình của tôi lớn hơn màn hình của bạn.", "My screen is bigger than yours."), s("Văn phòng hôm nay yên tĩnh hơn hôm qua.", "The office is quieter today than yesterday."), s("Cảm ơn sự giúp đỡ của bạn.", "Thank you for your help."), s("Không sao, đây là công việc của tôi.", "No problem, this is my job.")
  ]),
  unit("Meetings and Calendars", "A1", "polite", ["meetings", "calendar", "work"], [
    s("Vui lòng sắp xếp cuộc họp vào buổi sáng.", "Please schedule the meeting in the morning."), s("Bạn có thể tham gia cuộc họp ngày mai không?", "Can you attend tomorrow's meeting?"), s("Tôi nên chuẩn bị gì trước?", "What should I prepare in advance?"), s("Xin hãy mang hai bản báo cáo.", "Please bring two copies of the report."), s("Cuộc họp đã bắt đầu rồi.", "The meeting has already started."), s("Quản lý đang giới thiệu dự án mới.", "The manager is introducing the new project."), s("Tôi chưa đọc xong tài liệu này.", "I have not finished reading this document."), s("Vui lòng cho tôi năm phút.", "Please give me five minutes."), s("Chúng ta thảo luận vấn đề trước rồi quyết định thời gian.", "We will discuss the problem first and then decide the time."), s("Nếu khách hàng đồng ý thì chúng ta bắt đầu.", "If the client agrees, we will start."), s("Ai có thể ghi chép nội dung cuộc họp?", "Who can take meeting notes?"), s("Tôi có thể ghi chép nhưng cần một máy tính.", "I can take notes, but I need a computer."), s("Xin hãy viết những điểm chính lên bảng.", "Please write the main points on the board."), s("Vấn đề này quan trọng hơn vấn đề trước.", "This issue is more important than the previous one."), s("Chúng ta đã thảo luận vấn đề này rồi.", "We have discussed this issue before."), s("Nhưng tình hình bây giờ đã khác.", "But the situation is different now."), s("Hạn chót là ngày nào?", "Which day is the deadline?"), s("Hạn chót là thứ Sáu tuần sau.", "The deadline is next Friday."), s("Chúng ta phải hoàn thành đúng hạn.", "We must finish on time."), s("Nếu cần giúp đỡ thì hãy nói cho tôi biết.", "If you need help, let me know."), s("Sau cuộc họp vui lòng gửi email.", "Please send an email after the meeting."), s("Được, tôi nhất định sẽ gửi.", "Okay, I definitely will.")
  ]),
  unit("Phones, Messages, and Email", "A1", "question", ["communication", "email", "phone"], [
    s("Bạn đã nhận được email của tôi chưa?", "Have you received my email?"), s("Tôi nhận được rồi nhưng chưa trả lời.", "I received it but have not replied."), s("Xin hãy gửi tài liệu cho khách hàng.", "Please send the document to the client."), s("Khách hàng hỏi khi nào chúng ta trả lời.", "The client asked when we would reply."), s("Bạn có nghe thấy tiếng tôi không?", "Can you hear my voice?"), s("Tôi không nghe thấy, bạn nói lại nhé.", "I cannot hear you; please say it again."), s("Mạng có thể không ổn định lắm.", "The network may not be very stable."), s("Nếu mất kết nối thì chúng ta gửi tin nhắn.", "If we lose connection, we will send a message."), s("Đây là số điện thoại của khách hàng.", "This is the client's phone number."), s("Xin đừng gửi nhầm số điện thoại.", "Please do not send the wrong phone number."), s("Vừa rồi tôi đã gọi điện cho bạn.", "I called you just now."), s("Tôi không nghe thấy điện thoại.", "I did not hear the phone."), s("Bây giờ bạn có tiện nói chuyện không?", "Is now a convenient time to talk?"), s("Tôi đang họp nên không tiện.", "I am in a meeting, so it is not convenient."), s("Vui lòng gọi lại vào buổi chiều.", "Please call again in the afternoon."), s("Tiêu đề email đã rõ chưa?", "Is the email subject clear?"), s("Tôi đã viết tiêu đề rõ ràng rồi.", "I have written the subject clearly."), s("Tệp đính kèm này không mở được.", "This attachment cannot be opened."), s("Tôi có thể gửi lại tài liệu.", "I can resend the document."), s("Nếu không hiểu thì hãy hỏi tôi.", "If you do not understand, ask me."), s("Cảm ơn, lời giải thích của bạn rất hữu ích.", "Thanks, your explanation is very useful."), s("Tôi sẽ trả lời trước khi tan làm hôm nay.", "I will reply before I finish work today.")
  ]),
  unit("Tasks, Deadlines, and Work Status", "A1", "da", ["tasks", "deadlines", "status"], [
    s("Tôi đã làm xong nhiệm vụ này.", "I have finished this task."), s("Báo cáo vẫn chưa viết xong.", "The report is still not finished."), s("Bạn làm đến bước nào rồi?", "What step have you reached?"), s("Tôi đã hoàn thành một nửa.", "I have completed half of it."), s("Hạn chót sắp đến rồi.", "The deadline is coming soon."), s("Chúng ta phải nộp báo cáo hôm nay.", "We must submit the report today."), s("Nếu không kịp thì hãy báo ngay cho quản lý.", "If there is not enough time, tell the manager immediately."), s("Có thể tôi cần thêm một ngày.", "I may need one more day."), s("Xin lỗi, hôm qua tôi chưa đọc kỹ yêu cầu.", "Sorry, I did not read the requirements carefully yesterday."), s("Bây giờ tôi đã tìm ra vấn đề.", "I have found the problem now."), s("Vấn đề ở trang cuối của tài liệu.", "The problem is on the last page of the document."), s("Xin hãy sửa lỗi này.", "Please fix this error."), s("Tôi đã sửa xong rồi.", "I have fixed it."), s("Bạn có thể kiểm tra giúp tôi không?", "Can you check it for me?"), s("Tôi đã kiểm tra, không có vấn đề.", "I checked it; there is no problem."), s("Dự án này phức tạp hơn dự án trước.", "This project is more complicated than the previous one."), s("Nhưng chúng ta có thể hoàn thành.", "But we can finish it."), s("Xin hãy xử lý yêu cầu của khách hàng trước.", "Please handle the client's request first."), s("Sau đó sắp xếp tài liệu nội bộ.", "Then organize the internal documents."), s("Hôm nay tôi còn phải tham gia một cuộc họp.", "I still have to attend a meeting today."), s("Sau cuộc họp tôi sẽ tiếp tục làm.", "I will continue after the meeting."), s("Cảm ơn bạn đã nhắc, tôi sẽ nhớ.", "Thanks for reminding me; I will remember.")
  ]),
  unit("Workplace Problems and Misunderstandings", "A1", "passive", ["problems", "equipment", "repair"], [
    s("Máy tính của tôi đột nhiên tắt.", "My computer suddenly shut down."), s("Tôi không mở được tệp này.", "I cannot open this file."), s("Tệp có thể đã bị xóa.", "The file may have been deleted."), s("Ai có thể giúp tôi?", "Who can help me?"), s("Trước tiên hãy khởi động lại máy tính.", "First restart the computer."), s("Nếu vẫn không được thì liên hệ với kỹ thuật viên.", "If it still does not work, contact technical support."), s("Máy in bị kẹt giấy rồi.", "The printer is jammed."), s("Tôi đã lấy giấy ra.", "I have taken the paper out."), s("Nhưng máy vẫn chưa hoạt động.", "But the machine still does not work."), s("Quản lý đang tìm nhân viên sửa chữa.", "The manager is looking for a repair worker."), s("Có thể tôi đã nghe nhầm yêu cầu của bạn.", "I may have misunderstood your request."), s("Xin lỗi, hãy giải thích lại một lần nữa.", "Sorry, please explain it again."), s("Bạn nói hôm nay hay ngày mai?", "Do you mean today or tomorrow?"), s("Tôi nói sáng ngày mai.", "I mean tomorrow morning."), s("Nếu tôi hiểu sai thì hãy sửa cho tôi.", "If I misunderstood, please correct me."), s("Bây giờ chúng ta đã nói rõ rồi.", "Now we have made it clear."), s("Cách này đơn giản hơn cách cũ.", "This method is simpler than the old one."), s("Bạn có thể ghi các bước xuống.", "You can write down the steps."), s("Xin đừng xóa tệp gốc.", "Please do not delete the original file."), s("Tôi đã tìm thấy bản sao lưu.", "I have found the backup."), s("Vấn đề đã được giải quyết.", "The problem has been solved."), s("Lần sau chúng ta nên xác nhận trước.", "Next time we should confirm first.")
  ]),
  unit("Classroom Language and School Routines", "A1", "question", ["classroom", "school", "study"], [
    s("Thưa cô, chúng em có thể vào lớp không?", "Teacher, may we enter the classroom?"), s("Xin hãy mở sách trang mười.", "Please open the book to page ten."), s("Hôm nay chúng ta học ngữ pháp mới.", "Today we are studying new grammar."), s("Câu này nghĩa là gì?", "What does this sentence mean?"), s("Câu hỏi này trả lời thế nào?", "How do we answer this question?"), s("Câu trả lời ở trên bảng.", "The answer is on the board."), s("Bạn đã hiểu lời giải thích của giáo viên chưa?", "Did you understand the teacher's explanation?"), s("Tôi chỉ hiểu một phần.", "I only understood part of it."), s("Bạn có thể cho thêm một ví dụ không?", "Can you give another example?"), s("Được, tôi sẽ viết ở đây.", "Sure, I will write it here."), s("Hôm nay chúng ta có hai tiết học.", "We have two classes today."), s("Tiết đầu bắt đầu lúc chín giờ.", "The first class starts at nine."), s("Sau giờ học tôi đi thư viện.", "After class I will go to the library."), s("Tôi đã mượn ba quyển sách.", "I have borrowed three books."), s("Những quyển sách này là của trường.", "These books belong to the school."), s("Xin đừng viết lên sách.", "Please do not write in the books."), s("Nếu có câu hỏi thì hãy hỏi giáo viên.", "If you have a question, ask the teacher."), s("Tôi có nên luyện tập mỗi ngày không?", "Should I practice every day?"), s("Mỗi ngày luyện mười phút là tốt.", "Practicing ten minutes every day is good."), s("Phát âm của tôi rõ hơn trước rồi.", "My pronunciation is clearer than before."), s("Cảm ơn sự giúp đỡ của cô.", "Thank you for your help."), s("Hẹn gặp cô ngày mai.", "See you tomorrow.")
  ]),
  unit("Assignments, Exams, and Study Plans", "A1", "da", ["assignments", "exams", "study"], [
    s("Bạn đã làm xong bài tập chưa?", "Have you finished the homework?"), s("Tôi vẫn chưa làm xong.", "I still have not finished it."), s("Khi nào phải nộp bài tập?", "When is the homework due?"), s("Giáo viên nói phải nộp vào sáng mai.", "The teacher said it must be submitted tomorrow morning."), s("Tôi đã viết được hai trang.", "I have written two pages."), s("Nhưng phần kết luận vẫn chưa rõ.", "But the conclusion is still unclear."), s("Bạn đã từng làm bài tập kiểu này chưa?", "Have you done this kind of exercise before?"), s("Tôi đã từng làm nhưng lần này khó hơn.", "I have, but this time is harder."), s("Nếu không hiểu thì hãy thảo luận với bạn cùng lớp.", "If you do not understand, discuss it with a classmate."), s("Chúng ta nên xem ví dụ trước.", "We should look at the example first."), s("Kỳ thi quan trọng hơn bài tập không?", "Is the exam more important than the homework?"), s("Cả kỳ thi và bài tập đều quan trọng.", "Both the exam and homework are important."), s("Xin hãy viết câu trả lời lên giấy thi.", "Please write the answers on the exam paper."), s("Tôi không nhìn rõ câu hỏi cuối.", "I cannot see the last question clearly."), s("Tôi có thể xin một tờ giấy mới không?", "Can I have a new sheet of paper?"), s("Tôi đã từng thi tiếng Việt rồi.", "I have taken a Vietnamese exam before."), s("Điểm lần này tốt hơn lần trước.", "My score this time is better than last time."), s("Tối nào tôi cũng ôn bài một tiếng.", "I review for an hour every evening."), s("Cuối tuần tôi học với các bạn.", "I study with my classmates on weekends."), s("Cảm ơn bạn đã giải thích cho tôi.", "Thanks for explaining it to me."), s("Tôi nhất định sẽ nộp bài đúng hạn.", "I will definitely submit the assignment on time."), s("Sau kỳ thi chúng ta cùng ăn nhé.", "Let's eat together after the exam.")
  ]),
  unit("Campus Life and Group Projects", "A1", "condition", ["campus", "projects", "groups"], [
    s("Lớp học gần hơn thư viện.", "The classroom is closer than the library."), s("Trong khuôn viên có ba nhà ăn.", "There are three dining halls on campus."), s("Bạn ở nhóm nào?", "Which group are you in?"), s("Tôi là thành viên của nhóm hai.", "I am a member of group two."), s("Chúng tôi đang làm một dự án.", "We are working on a project."), s("Dự án này thú vị hơn dự án trước.", "This project is more interesting than the last one."), s("Xin hãy ghi ý tưởng của bạn xuống.", "Please write down your idea."), s("Ý tưởng của tôi khác ý tưởng của bạn.", "My idea is different from yours."), s("Nếu mọi người đồng ý thì chúng ta làm như vậy.", "If everyone agrees, we will do it this way."), s("Bạn có thể phụ trách phần đầu không?", "Can you be responsible for the first part?"), s("Tôi có thể nhưng cần tài liệu của bạn.", "I can, but I need your materials."), s("Tài liệu đã được gửi vào nhóm rồi.", "The materials have been sent to the group."), s("Tôi vẫn chưa đọc hết tài liệu.", "I still have not read all the materials."), s("Chúng ta chia nhiệm vụ trước rồi bắt đầu.", "We will divide the tasks first and then start."), s("Ai có thể thuyết trình cuối cùng?", "Who can give the final presentation?"), s("Tôi đã từng làm bài thuyết trình như vậy.", "I have given that kind of presentation before."), s("Nhưng lần này tôi muốn làm cùng bạn.", "But this time I want to do it with you."), s("Giáo viên nói kế hoạch của chúng ta rất rõ.", "The teacher said our plan is very clear."), s("Vấn đề phức tạp hơn chúng ta nghĩ.", "The problem is more complicated than we thought."), s("Chúng ta nên sắp xếp lại thời gian.", "We should rearrange the schedule."), s("Dự án đã hoàn thành rồi.", "The project is finished."), s("Mọi người đã làm rất tốt.", "Everyone did a very good job.")
  ]),
  unit("Illness, Injuries, and Appointments", "A1", "reason", ["health", "doctor", "appointments"], [
    s("Hôm nay tôi thấy không khỏe.", "I do not feel well today."), s("Vì bị sốt nên tôi không thể đi làm.", "Because I have a fever, I cannot go to work."), s("Đầu tôi rất đau.", "My head hurts a lot."), s("Tay bạn bị làm sao vậy?", "What happened to your hand?"), s("Hôm qua tôi vô tình va vào bàn.", "Yesterday I accidentally hit the table."), s("Bây giờ tay còn đau không?", "Does your hand still hurt?"), s("Hôm nay đỡ hơn hôm qua nhiều.", "It is much better today than yesterday."), s("Tôi có nên đi bệnh viện không?", "Should I go to the hospital?"), s("Nếu đau nhiều thì hãy đi bệnh viện.", "If it hurts badly, go to the hospital."), s("Xin hãy nói cho bác sĩ biết bạn bị thương khi nào.", "Please tell the doctor when you were injured."), s("Tôi chưa từng bị vết thương như vậy.", "I have never had an injury like that."), s("Bác sĩ nói tôi cần nghỉ vài ngày.", "The doctor said I need to rest for a few days."), s("Tôi đã đặt lịch khám vào buổi chiều.", "I have made an appointment for the afternoon."), s("Xin hãy mang theo giấy tờ tùy thân.", "Please bring your identification."), s("Bệnh viện xa công ty hơn trường học.", "The hospital is farther from the company than the school."), s("Tôi có thể xin nghỉ một ngày không?", "May I take one day off?"), s("Được, bạn nên nghỉ ngơi.", "Of course, you should rest."), s("Tôi sẽ gửi giấy của bác sĩ cho quản lý.", "I will send the doctor's note to the manager."), s("Đừng lo, tôi nhất định sẽ khỏe lại.", "Do not worry; I will definitely get better."), s("Bạn đã từng uống thuốc này chưa?", "Have you taken this medicine before?"), s("Tôi đã uống nhưng trước tiên phải hỏi bác sĩ.", "I have, but we should ask the doctor first."), s("Cảm ơn bạn đã đi bệnh viện cùng tôi.", "Thank you for going to the hospital with me.")
  ]),
  unit("Minor Accidents and Asking for Help", "A1", "passive", ["accidents", "help", "safety"], [
    s("Bạn có sao không? Vừa rồi có chuyện gì?", "Are you okay? What happened just now?"), s("Tôi bị trượt chân ở cầu thang.", "I slipped on the stairs."), s("Chân bạn có đau không?", "Does your leg hurt?"), s("Chân hơi đau nhưng tôi đi được.", "My leg hurts a little, but I can walk."), s("Xin hãy ngồi xuống, đừng đứng ngay.", "Please sit down; do not stand up immediately."), s("Nếu bạn không đi được thì tôi gọi xe cứu thương.", "If you cannot walk, I will call an ambulance."), s("Tôi đã lau khô nước trên sàn.", "I have dried the water on the floor."), s("Sàn nhà vừa rồi rất trơn.", "The floor was very slippery just now."), s("Xin hãy rào khu vực này lại.", "Please block off this area."), s("Bạn có bị thương không?", "Are you injured?"), s("Tôi không bị thương nhưng túi bị rách.", "I am not injured, but my bag is torn."), s("Cái túi có thể bị cửa kẹp hỏng.", "The bag may have been damaged by the door."), s("Bạn có cần tôi tìm nhân viên không?", "Do you need me to find a staff member?"), s("Có, xin hãy giúp tôi gọi điện.", "Yes, please help me make a call."), s("Xin hãy nói cho nhân viên biết tai nạn ở đâu.", "Please tell the staff where the accident is."), s("Tai nạn ở cạnh cầu thang tầng hai.", "The accident is beside the second-floor stairs."), s("Nếu cần tôi có thể làm nhân chứng.", "If necessary, I can be a witness."), s("Tôi đã ghi lại thời gian và địa chỉ.", "I have written down the time and address."), s("Xin đừng di chuyển người bị thương.", "Please do not move the injured person."), s("Bác sĩ sắp đến rồi.", "The doctor will arrive soon."), s("Cảm ơn bạn đã giúp tôi kịp thời.", "Thank you for helping me promptly."), s("Nếu không chắc chắn, hãy nhờ nhân viên kiểm tra.", "If you are unsure, ask a staff member to check.")
  ]),
  unit("Serious Accidents and Emergency Services", "A2", "passive", ["emergency", "hospital", "police"], [
    s("Ở đây vừa xảy ra một vụ tai nạn giao thông.", "A traffic accident just happened here."), s("Có người bị thương, hãy gọi điện ngay.", "Someone is injured; call immediately."), s("Xe cứu thương khi nào đến?", "When will the ambulance arrive?"), s("Xe cứu thương đang trên đường đến.", "The ambulance is on the way."), s("Xin hãy cho tôi biết địa chỉ của bạn.", "Please tell me your address."), s("Địa chỉ là con đường phía sau trường học.", "The address is the road behind the school."), s("Người bị thương còn nói được không?", "Can the injured person still speak?"), s("Anh ấy còn nói được nhưng chân rất đau.", "He can still speak, but his leg hurts badly."), s("Xin đừng để anh ấy đứng dậy.", "Please do not let him stand up."), s("Nếu anh ấy bất tỉnh thì hãy báo cho bác sĩ.", "If he loses consciousness, tell the doctor."), s("Tôi đã chụp lại hiện trường.", "I have photographed the scene."), s("Nhưng xin đừng đến gần chỗ nguy hiểm.", "But please do not go near the dangerous place."), s("Cảnh sát đã đến hiện trường.", "The police have arrived at the scene."), s("Cảnh sát đang hỏi các nhân chứng.", "The police are questioning witnesses."), s("Tôi thấy một chiếc xe đi từ bên phải đến.", "I saw a car come from the right."), s("Tôi không biết tên tài xế.", "I do not know the driver's name."), s("Tôi chưa từng gặp tai nạn như thế này.", "I have never encountered an accident like this."), s("Xin hãy cho cảnh sát xem giấy tờ của bạn.", "Please show your documents to the police."), s("Bệnh viện xa hơn nhưng đường đi nhanh.", "The hospital is farther, but the route is fast."), s("Chúng ta phải giữ bình tĩnh.", "We must remain calm."), s("Xin mọi người hãy đứng ở nơi an toàn.", "Everyone, please stand in a safe place."), s("Cảm ơn sự hợp tác của bạn.", "Thank you for your cooperation.")
  ]),
  unit("Incident Reports, Solutions, and Review", "A2", "report", ["reports", "solutions", "review"], [
    s("Trước tiên hãy nói thời gian xảy ra tai nạn.", "First state when the accident happened."), s("Tai nạn xảy ra khoảng ba giờ chiều.", "The accident happened around three in the afternoon."), s("Sau đó hãy nói bạn đang ở đâu.", "Then state where you were."), s("Lúc đó tôi đang đợi xe ở cổng trường.", "At that time I was waiting for a vehicle at the school gate."), s("Tôi thấy một người chạy qua đường.", "I saw someone run across the road."), s("Vì đường trơn nên người đó bị ngã.", "Because the road was slippery, the person fell."), s("Tôi đã gọi xe cứu thương ngay.", "I called an ambulance immediately."), s("Sau khi xe cứu thương đến, chúng tôi đưa người đó vào bệnh viện.", "After the ambulance came, we took the person to the hospital."), s("Bác sĩ nói vết thương không quá nghiêm trọng.", "The doctor said the injury was not too serious."), s("Nhưng người đó nên nghỉ vài ngày.", "But the person should rest for a few days."), s("Xin lỗi, tôi đã không nhìn thấy nước trên sàn ngay.", "Sorry, I did not see the water on the floor immediately."), s("Không sao, điều quan trọng là bây giờ an toàn rồi.", "It is okay; what matters is that it is safe now."), s("Chúng ta phải dọn sạch hiện trường.", "We must clean the scene."), s("Nếu sau này trời lại mưa thì nên đặt biển cảnh báo.", "If it rains again later, we should put up a warning sign."), s("Tôi sẽ gửi báo cáo cho quản lý.", "I will send the report to the manager."), s("Quản lý nói chúng ta đã xử lý rất tốt.", "The manager said we handled it well."), s("Lần này chúng ta xử lý nhanh hơn lần trước nhiều.", "This time we handled it much faster than last time."), s("Bạn đã từng viết báo cáo tai nạn chưa?", "Have you written an incident report before?"), s("Tôi đã từng viết nhưng lần này phức tạp hơn.", "I have, but this time is more complicated."), s("Xin hãy viết rõ tất cả thông tin quan trọng.", "Please write all important information clearly."), s("Cảm ơn mọi người, chúng ta đã giải quyết vấn đề.", "Thanks everyone; we solved the problem."), s("Khi gặp nguy hiểm, hãy bảo vệ mình trước tiên.", "When facing danger, protect yourself first.")
  ])
];

if (units.length !== 20 || units.some((item) => item.sentences.length !== 22)) throw new Error("Vietnamese course must contain exactly 20 units of 22 sentences.");

function buildLesson(item, index) {
  return {
    language: "vi",
    baseLanguage: "en",
    title: `Unit ${String(index + 1).padStart(2, "0")}: ${item.title}`,
    description: `Practical Vietnamese for ${item.title.toLowerCase()}.`,
    source: "ai_generated",
    level: item.level,
    tags: [`unit:${String(index + 1).padStart(2, "0")}`, ...item.tags],
    sentences: item.sentences.map(([text, translation]) => {
      const words = vocab.filter(([surface]) => text.includes(surface)).slice(0, 5).map(([surface, meaning, role]) => ({ surface, lemma: surface, meaning, role }));
      const extraRules = [
        /có thể|muốn|cần|nên|phải/.test(text) ? "modal" : null,
        /hơn|bằng|khác/.test(text) ? "comparison" : null
      ].filter((id) => id && id !== item.ruleId);
      const grammar = [item.ruleId, ...extraRules].map((ruleId) => {
        const [title, overview] = rules[ruleId];
        return { pattern: title, meaning: overview, ruleId, explanation: `This sentence gives a practical ${item.title.toLowerCase()} example of the rule.` };
      });
      return {
        text,
        translation,
        words,
        grammar
      };
    })
  };
}

const lessons = units.map(buildLesson);
const grammarGuide = {
  schemaVersion: 1,
  rules: Object.entries(rules).map(([id, [title, overview, mistake, unitIndexes]]) => ({
    id,
    title,
    overview,
    situations: [{ title: "Core use", explanation: overview, unitIndexes }],
    contrasts: [mistake],
    commonMistakes: [mistake]
  }))
};
const pack = {
  type: "fydor_pack",
  schemaVersion: 1,
  id: "humongous-vietnamese-daily-v1",
  title: "Humongous Vietnamese: Daily Life, Work & School",
  description: "A 440-sentence Vietnamese course for English speakers, focused on daily life, workplace and school scenarios, accidents, emergencies, and practical grammar.",
  author: { name: "Fydor Community" },
  version: "2.0.0",
  license: "CC BY 4.0",
  language: "vi",
  baseLanguage: "en",
  level: "A0-A2",
  tags: ["vietnamese", "english", "daily-life", "work", "school", "accidents", "emergency", "grammar"],
  createdAt: "2026-07-17T00:00:00.000Z",
  updatedAt: "2026-07-18T00:00:00.000Z",
  unitManifest: { schemaVersion: 1, units: lessons.map((lesson, position) => ({ id: `unit-${String(position + 1).padStart(2, "0")}`, title: lesson.title, position, lessonIndexes: [position] })) },
  grammarGuide,
  lessons
};

const output = path.resolve("packs/humongous-vietnamese-v1.fydorpack");
fs.writeFileSync(output, `${JSON.stringify(pack, null, 2)}\n`);
console.log(`Wrote ${output}: ${lessons.length} units, ${lessons.length * 22} sentences, ${grammarGuide.rules.length} grammar rules.`);
