use crate::{db, models::{Collection, CollectionInput, Course, CourseInput, CourseUnit, LanguagePair}};
use anyhow::{bail, Result};
use rusqlite::{params, Connection, OptionalExtension};
use tauri::State;

#[tauri::command]
pub fn get_language_pairs(state: State<db::AppState>) -> Result<Vec<LanguagePair>, String> {
    let conn = state.conn.lock().map_err(|e| e.to_string())?;
    let mut statement = conn.prepare("SELECT p.id, t.code, b.code FROM language_pairs p JOIN languages t ON t.id=p.target_language_id JOIN languages b ON b.id=p.base_language_id ORDER BY t.name,b.name").map_err(|e| e.to_string())?;
    let pairs = statement.query_map([], |row| Ok(LanguagePair { id: row.get(0)?, target_language: row.get(1)?, base_language: row.get(2)? })).map_err(|e| e.to_string())?.collect::<rusqlite::Result<Vec<_>>>().map_err(|e| e.to_string())?;
    Ok(pairs)
}
#[tauri::command]
pub fn get_active_language_pair(state: State<db::AppState>) -> Result<String, String> { let c=state.conn.lock().map_err(|e|e.to_string())?; c.query_row("SELECT value FROM user_settings WHERE key='active_language_pair_id'", [], |r|r.get(0)).map_err(|e|e.to_string()) }
#[tauri::command]
pub fn set_active_language_pair(language_pair_id: String,state: State<db::AppState>) -> Result<(), String> { let c=state.conn.lock().map_err(|e|e.to_string())?; require_pair(&c,&language_pair_id).map_err(|e|e.to_string())?; c.execute("INSERT INTO user_settings(key,value,updated_at) VALUES('active_language_pair_id',?1,?2) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at",params![language_pair_id,db::now()]).map_err(|e|e.to_string())?;Ok(()) }
#[tauri::command]
pub fn create_course(input: CourseInput,state: State<db::AppState>) -> Result<Course,String> { let c=state.conn.lock().map_err(|e|e.to_string())?; require_pair(&c,&input.language_pair_id).map_err(|e|e.to_string())?; if input.title.trim().is_empty(){return Err("Course title is required.".into())}; let course=Course{id:db::id(),language_pair_id:input.language_pair_id,title:input.title.trim().into(),description:input.description};c.execute("INSERT INTO courses(id,language_pair_id,title,description,created_at,updated_at) VALUES(?1,?2,?3,?4,?5,?5)",params![course.id,course.language_pair_id,course.title,course.description,db::now()]).map_err(|e|e.to_string())?;Ok(course) }
#[tauri::command]
pub fn create_course_unit(course_id:String,title:String,description:Option<String>,state:State<db::AppState>)->Result<CourseUnit,String>{let c=state.conn.lock().map_err(|e|e.to_string())?;let position:i64=c.query_row("SELECT COALESCE(MAX(position)+1,0) FROM course_units WHERE course_id=?1",[&course_id],|r|r.get(0)).map_err(|e|e.to_string())?;let u=CourseUnit{id:db::id(),course_id,title,description,position};c.execute("INSERT INTO course_units(id,course_id,title,description,position,created_at,updated_at) VALUES(?1,?2,?3,?4,?5,?6,?6)",params![u.id,u.course_id,u.title,u.description,u.position,db::now()]).map_err(|e|e.to_string())?;Ok(u)}
#[tauri::command]
pub fn add_lesson_to_unit(unit_id:String,lesson_id:String,state:State<db::AppState>)->Result<(),String>{let c=state.conn.lock().map_err(|e|e.to_string())?;let pair:Option<String>=c.query_row("SELECT c.language_pair_id FROM course_units u JOIN courses c ON c.id=u.course_id WHERE u.id=?1",[&unit_id],|r|r.get(0)).optional().map_err(|e|e.to_string())?;let Some(pair)=pair else{return Err("Unknown unit.".into())};let valid:bool=c.query_row("SELECT EXISTS(SELECT 1 FROM lessons WHERE id=?1 AND language_pair_id=?2)",params![lesson_id,pair],|r|r.get(0)).map_err(|e|e.to_string())?;if !valid{return Err("Lesson belongs to a different language workspace.".into())};let pos:i64=c.query_row("SELECT COALESCE(MAX(position)+1,0) FROM unit_lessons WHERE unit_id=?1",[&unit_id],|r|r.get(0)).map_err(|e|e.to_string())?;c.execute("INSERT INTO unit_lessons(unit_id,lesson_id,position,created_at) VALUES(?1,?2,?3,?4) ON CONFLICT(unit_id,lesson_id) DO NOTHING",params![unit_id,lesson_id,pos,db::now()]).map_err(|e|e.to_string())?;Ok(())}
#[tauri::command]
pub fn reorder_unit_lessons(unit_id:String,lesson_ids:Vec<String>,state:State<db::AppState>)->Result<(),String>{let mut c=state.conn.lock().map_err(|e|e.to_string())?;let tx=c.transaction().map_err(|e|e.to_string())?;let count:i64=tx.query_row("SELECT COUNT(*) FROM unit_lessons WHERE unit_id=?1",[&unit_id],|r|r.get(0)).map_err(|e|e.to_string())?;if count!=lesson_ids.len()as i64{return Err("Reorder must include every lesson exactly once.".into())}tx.execute("UPDATE unit_lessons SET position=-position-1 WHERE unit_id=?1",[&unit_id]).map_err(|e|e.to_string())?;for(i,id)in lesson_ids.iter().enumerate(){tx.execute("UPDATE unit_lessons SET position=?1 WHERE unit_id=?2 AND lesson_id=?3",params![i as i64,unit_id,id]).map_err(|e|e.to_string())?;}tx.commit().map_err(|e|e.to_string())?;Ok(())}
#[tauri::command]
pub fn create_collection(input:CollectionInput,state:State<db::AppState>)->Result<Collection,String>{let c=state.conn.lock().map_err(|e|e.to_string())?;require_pair(&c,&input.language_pair_id).map_err(|e|e.to_string())?;if !matches!(input.kind.as_str(),"manual"|"smart"){return Err("Collection kind must be manual or smart.".into())};let x=Collection{id:db::id(),language_pair_id:input.language_pair_id,title:input.title,kind:input.kind,query_json:input.query_json};c.execute("INSERT INTO collections(id,language_pair_id,title,kind,query_json,created_at,updated_at) VALUES(?1,?2,?3,?4,?5,?6,?6)",params![x.id,x.language_pair_id,x.title,x.kind,x.query_json,db::now()]).map_err(|e|e.to_string())?;Ok(x)}
fn require_pair(c:&Connection,id:&str)->Result<()> {let found:bool=c.query_row("SELECT EXISTS(SELECT 1 FROM language_pairs WHERE id=?1)",[id],|r|r.get(0))?;if !found{bail!("Unknown language pair.")}Ok(())}
